
# exclude directories/files from conversion
exclude: [
  ".bundle",
  ".husky",
  "vendor",
  ".gitignore",
  "Gemfile",
  "Gemfile.lock",
  "Makefile",
  "package.json",
  "package-lock.json",
  "postcss.config.js",
  "README.md",
  "tsconfig.json",
  "tsconfig.development.json",
  "tsconfig.internal_util.json",
  "tsconfig.production.json"
  ]

# keep these files (in the destination directory)
# default: keep_files: [".git", ".svn"]
keep_files: []

# set the timezone for site generation
timezone: Europe/Berlin

# serving (locally for development)
port: 4000
host: 0.0.0.0
