
# where is the actual content?
source: content

# keep these files (in the destination directory)
# default: keep_files: [".git", ".svn"]
keep_files: ["assets", "asset_manifest.json"]

# set the timezone for site generation
timezone: Europe/Berlin

# serving (locally for development)
port: 4000
host: 0.0.0.0
