/* PostCSS config file
 *
 * PostCSS is used to post-process CSS files, generated by sass.
 *
 * This config will use the following plugins to create a "production-ready"
 * stylesheet:
 *  - purgecss (get rid of CSS-code that is not used by the html sources)
 *  - autoprefixer (add vendor-specific prefixes)
 *  - cssnano (optimize/minimize the stylesheet)
 */
module.exports = {
  plugins: [
    require("@fullhuman/postcss-purgecss")({
      content: ["./**/*.html"],
      fontFace: true, // default: false
      keyframes: true, // default: false
      variables: true, // default: false
      rejected: false, // turn "true" to actually see list of removed items
      // safelist: [],  // ALWAYS include these
      blocklist: [], // NEVER include these
    }),
    /* TODO: "autoprefixer" relies on "browserslist" and may be controlled
     *       using a ".browserslistrc" file for configuration.
     *       "browserslist" provides sane defaults, but these default may be
     *       *too inclusive* and can be turned down.
     */
    require("autoprefixer")(),
    require("cssnano")(),
  ],
};
